apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-service-app
spec:
  replicas: 2  
  selector:
    matchLabels:
      app: user-service-app
  template:
    metadata:
      labels:
        app: user-service-app
    spec:
      containers:
        - name: user-service-app
          image: burbasdocker/user-service:latest 
          ports:
            - containerPort: 3000 
      imagePullSecrets:
        - name: dockerhubcredentials

---

apiVersion: v1
kind: Service
metadata:
  name: user-service-service
spec:
  selector:
    app: user-service-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
  type: LoadBalancer  
