name: Docker Image Build and Push

on:
  push:
    branches:
      - main  # Adjust as per your branch name
  # You can add additional triggers like pull requests or specific tags if needed

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Login to Docker Hub
        run: echo "${{ secrets.DOCKER_HUB_TOKEN }}" | docker login -u ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}
      
      - name: Build the Docker image
        run: docker build -t burbasdocker/user-service:latest .
        # Replace 'your-docker-username' and 'your-docker-repo' with your Docker Hub username and repository name

      - name: Push the Docker image to Docker Hub
        run: docker push burbasdocker/user-service:latest
        # Replace 'your-docker-username' and 'your-docker-repo' with your Docker Hub username and repository name
