name: Docker Image Build and Push

on:
  push:
    branches:
      - main  # Adjust as per your branch name
      - feature/*
  # You can add additional triggers like pull requests or specific tags if needed

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USER_NAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}
      
      - name: Build the Docker image
        run: docker build -t burbasdocker/user-service:latest .
        # Replace 'your-docker-username' and 'your-docker-repo' with your Docker Hub username and repository name

      - name: Push the Docker image to Docker Hub
        run: docker push burbasdocker/user-service:latest
        # Replace 'your-docker-username' and 'your-docker-repo' with your Docker Hub username and repository name

      - name: Update AWS CLI
        run: |
          sudo apt-get update
          sudo apt-get install -y awscli
      
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-north-1
      
      - name: Update Kubernetes config for Amazon EKS
        run: aws eks update-kubeconfig --name gihan-iit --region eu-north-1

      - name: Apply Kubernetes manifest changes to EKS
        run: kubectl apply -f k8s-manifest.yaml
